//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystemEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Borrowed
    {
        public int BorrowID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime Issued_date { get; set; }
        public System.DateTime Return_date { get; set; }
        public int Status { get; set; }
    
        public virtual TBL_Book TBL_Book { get; set; }
        public virtual TBL_User TBL_User { get; set; }
    }
}
