//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystemEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Book()
        {
            this.TBL_Borrowed = new HashSet<TBL_Borrowed>();
        }
    
        public int Book_ID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Page_Count { get; set; }
    
        public virtual TBL_Category TBL_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Borrowed> TBL_Borrowed { get; set; }
    }
}
